#
# Release Drafter Configuration
#
# https://github.com/release-drafter/release-drafter#configuration

name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'enhancement'
      - 'feature-request'
      - '🆕 feature request'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - '🐛 bug'
  - title: '🧰 Maintenance'
    label: 'cocoapod'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # What's New
  $CHANGES
