included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - file_length
    - cyclomatic_complexity
    - variable_name
    - todo
    - line_length
    - type_body_length
    - function_body_length
    - empty_count

shorthand_operator: warning
superfluous_disable_command: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

function_parameter_count:
   warning: 7
   error: 10
